cmd_/root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/rtusb_data.o := arm-xilinx-linux-gnueabi-gcc -Wp,-MD,/root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/.rtusb_data.o.d  -nostdinc -isystem /root/CodeSourcery/bin/../lib/gcc/arm-xilinx-linux-gnueabi/4.7.2/include -I/root/zybo_gpio/linux-digilent/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include /root/zybo_gpio/linux-digilent/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-zynq/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=7601U -DRESOURCE_PRE_ALLOC -I/root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/include -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DSTATS_COUNT_SUPPORT -DMT7601U -DMT7601 -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRX_DMA_SCATTER -DVCORECAL_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DRTMP_INTERNAL_TX_ALC -DCONFIG_ANDES_SUPPORT -DDPD_CALIBRATION_SUPPORT -DCONFIG_RX_CSO_SUPPORT -DRTMP_FREQ_CALIBRATION_SUPPORT  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(rtusb_data)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7601Usta)" -c -o /root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/.tmp_rtusb_data.o /root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/rtusb_data.c

source_/root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/rtusb_data.o := /root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/rtusb_data.c

deps_/root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/rtusb_data.o := \

/root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/rtusb_data.o: $(deps_/root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/rtusb_data.o)

$(deps_/root/zybo_gpio/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../common/rtusb_data.o):
